-- Enable PostgreSQL extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. network_users Table
CREATE TABLE public.network_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT UNIQUE NOT NULL,
  pin TEXT NOT NULL,
  address TEXT,
  firm_name TEXT,
  city TEXT,
  area TEXT,
  city_covers JSONB, -- Stored as JSONB for better performance
  area_covers JSONB, -- Stored as JSONB for better performance
  default_city TEXT,
  default_area TEXT,
  default_type TEXT,
  default_unit TEXT DEFAULT 'Gaj',
  default_privacy TEXT CHECK (default_privacy IN ('public', 'private')) DEFAULT 'public',
  token TEXT UNIQUE,
  created_on TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_network_users_phone ON public.network_users (phone);
CREATE INDEX idx_network_users_token ON public.network_users (token);

-- 2. network_properties Table
CREATE TABLE public.network_properties (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id BIGINT NOT NULL REFERENCES public.network_users(id) ON DELETE CASCADE,
  city TEXT NOT NULL,
  area TEXT NOT NULL,
  type TEXT NOT NULL,
  description TEXT,
  note_private TEXT,
  size_min NUMERIC(10,2),
  size_max NUMERIC(10,2),
  size_unit TEXT DEFAULT 'Gaj',
  price_min NUMERIC(15,2),
  price_max NUMERIC(15,2),
  location TEXT,
  location_accuracy TEXT,
  landmark_location TEXT,
  landmark_location_distance INTEGER,
  is_public BOOLEAN DEFAULT true,
  tags TEXT,
  highlights TEXT,
  image_urls TEXT,
  public_rating NUMERIC(2,1) DEFAULT 0,
  my_rating NUMERIC(2,1) DEFAULT 0,
  created_on TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_on TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_network_properties_owner ON public.network_properties (owner_id);
CREATE INDEX idx_network_properties_city ON public.network_properties (city);
CREATE INDEX idx_network_properties_area ON public.network_properties (area);
CREATE INDEX idx_network_properties_type ON public.network_properties (type);
CREATE INDEX idx_network_properties_public ON public.network_properties (is_public);

-- Function to handle updated_on automatically
CREATE OR REPLACE FUNCTION public.set_updated_on()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_on = CURRENT_TIMESTAMP;
   RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_network_properties
BEFORE UPDATE ON public.network_properties
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_on();

-- Cache Revalidation Trigger
CREATE OR REPLACE FUNCTION public.revalidate_public_cache()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
DECLARE
  revalidate_url text := 'https://www.mylistings.in/api/revalidate?token=sb_revalidate_2026_auto';
BEGIN
  -- We don't want to block the DB update if the network call fails, 
  -- but since it's an HTTP POST, we'll try it.
  -- Using pg_net for asynchronous non-blocking calls
  PERFORM net.http_post(
    url := revalidate_url,
    body := '{}'::jsonb
  );
  RETURN NEW;
END;
$function$;

CREATE TRIGGER tr_revalidate_cache
AFTER INSERT OR UPDATE OR DELETE ON public.network_properties
FOR EACH ROW EXECUTE FUNCTION public.revalidate_public_cache();

-- 3. network_properties_view (View)
CREATE OR REPLACE VIEW public.network_properties_view AS
SELECT 
  p.*,
  u.name AS owner_name,
  u.phone AS owner_phone,
  u.firm_name AS owner_firm_name
FROM public.network_properties p
LEFT JOIN public.network_users u ON p.owner_id = u.id;

-- 4. network_favorites Table
CREATE TABLE public.network_favorites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES public.network_users(id) ON DELETE CASCADE,
  property_id BIGINT NOT NULL REFERENCES public.network_properties(id) ON DELETE CASCADE,
  user_note TEXT,
  is_favourite BOOLEAN DEFAULT true,
  created_on TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (user_id, property_id)
);

CREATE INDEX idx_network_favorites_user ON public.network_favorites (user_id);
CREATE INDEX idx_network_favorites_property ON public.network_favorites (property_id);
